Prepare for running locally in Docker
zicht/z-plugin-systemjs pull request #2
Opened 2020-09-08 09:12 UTC by 7ochem

Detect if there is a node_modules/.bin/systemjs-bundle script, otherwise run globally

Also updated the maintainers

2020-09-09 07:26 UTC, boudewijn-zicht requested changes

2020-09-09 07:26 UTC, boudewijn-zicht commented on systemjs/Plugin.php
> -                        }
Er is geen equivalent voor deze melding meer... maar dit kan nog wel voorkomen.  Waarom is dit weggehaald?

2020-09-10 09:52 UTC, 7ochem commented on systemjs/Plugin.php
> -                        }
Omdat `node_modules/.bin/systemjs-bundle` nog niet bestaat voordat `npm install` is gedaan. Het eerste dat tijdens een deploy gebeurt is de versie op de target env checken met `z env:version`. Elk z command triggered het valideren van de config. Voordat `npm install` is gedaan, kun je dus geen z command meer uitvoeren hierdoor.

Overigens is dit de enige plugin die een check doet. Andere plugins checken niet of de te gebruiken tool wel bestaat (composer, npm, node, uglifyjs, zsass, sass, bower, etc...). Bij die andere plugins kom je er achter dat de executable niet beschikbaar is door een error vanuit je systeem. Dat lijkt mij in dit geval ook afdoende.

2020-09-11 12:42 UTC, boudewijn-zicht approved these changes

2020-09-17 14:21 UTC, merged